server:
  port: 7070
  servlet:
    session:
      cookie:
        name: YSESSION
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      access-token-uri: http://localhost:9191/oauth/token
      user-authorization-uri: http://localhost:9191/oauth/authorize
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token