
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcloud_rent?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: rent
server:
  port: 8181
