server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuwaanpandey/spring-cloud-config-store
          #username: "dsd"
          #passphrase: "dsd"
          search-paths: '*service'